export const ADD_BURGER = 'ADD_BURGER';
export const REMOVE_BURGER = 'REMOVE_BURGER';
export const CLEAR_BURGERS = 'CLEAR_BURGERS';
export const SET_BURGERS = 'SET_BURGERS';
export const SORT_BURGER = 'SORT_BURGER';
export const SET_BURGER_INGREDIENTS = 'SET_BURGER_INGREDIENTS';
export const ADD_BURGER_INGREDIENT = 'ADD_BURGER_INGREDIENT';
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT';
export const MOVE_BURGER_INGREDIENT = 'MOVE_BURGER_INGREDIENT';

export const ADD_MENU_INGREDIENT = 'ADD_MENU_INGREDIENT';
export const REMOVE_MENU_INGREDIENT = 'REMOVE_MENU_INGREDIENT';

export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CHANGE_SELECTED_BURGER = 'CHANGE_SELECTED_BURGER';
