export const ADD_BURGER = 'ADD_BURGER';
export const REMOVE_BURGER = 'REMOVE_BURGER';
export const CLEAR_BURGER = 'CLEAR_BURGER';
export const SET_BURGERS = 'SET_BURGERS';
export const SORT_BURGER = 'SORT_BURGER';
export const SET_BURGER_INGREDIENTS = 'SET_BURGER_INGREDIENTS';
export const ADD_BURGER_INGREDIENT = 'ADD_BURGER_INGREDIENT';
export const REMOVE_BURGER_INGREDIENT = 'REMOVE_BURGER_INGREDIENT';
export const MOVE_BURGER_INGREDIENT = 'MOVE_BURGER_INGREDIENT';

export const ADD_MENU_INGREDIENT = 'ADD_MENU_INGREDIENT';
export const REMOVE_MENU_INGREDIENT = 'REMOVE_MENU_INGREDIENT';
